/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface LockBoxInterface extends ethers.utils.Interface {
  functions: {
    "approveAsset(uint256)": FunctionFragment;
    "boxFee()": FunctionFragment;
    "cancelLockBox(uint256)": FunctionFragment;
    "claimAsset(uint256)": FunctionFragment;
    "counter()": FunctionFragment;
    "createLockBox(uint8,address,uint256,uint256,uint8,address,uint256,uint256,uint256)": FunctionFragment;
    "lockAsset(uint256)": FunctionFragment;
    "lockBoxInfo(uint256)": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "updateBoxFee(uint256)": FunctionFragment;
    "withdrawFunds()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "approveAsset",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "boxFee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "cancelLockBox",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimAsset",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "counter", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "createLockBox",
    values: [
      BigNumberish,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "lockAsset",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lockBoxInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateBoxFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFunds",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "approveAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "boxFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelLockBox",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claimAsset", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "counter", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createLockBox",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lockAsset", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lockBoxInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateBoxFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFunds",
    data: BytesLike
  ): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export type OwnershipTransferredEvent = TypedEvent<
  [string, string] & { previousOwner: string; newOwner: string }
>;

export class LockBox extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: LockBoxInterface;

  functions: {
    approveAsset(
      _id: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    boxFee(overrides?: CallOverrides): Promise<[BigNumber]>;

    cancelLockBox(
      _id: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    claimAsset(
      _id: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    counter(overrides?: CallOverrides): Promise<[BigNumber]>;

    createLockBox(
      _assetAtype: BigNumberish,
      _assetAaddress: string,
      _assetAID: BigNumberish,
      _assetAQuantity: BigNumberish,
      _assetBtype: BigNumberish,
      _assetBaddress: string,
      _assetBID: BigNumberish,
      _assetBQuantity: BigNumberish,
      _expiryTime: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    lockAsset(
      _id: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    lockBoxInfo(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        BigNumber,
        number,
        [
          number,
          string,
          string,
          BigNumber,
          BigNumber,
          number,
          number,
          number,
          string
        ] & {
          assetType: number;
          owner: string;
          assetAddress: string;
          assetID: BigNumber;
          assetQuantity: BigNumber;
          lockStatus: number;
          approvalStatus: number;
          claimStatus: number;
          claimedBy: string;
        },
        [
          number,
          string,
          string,
          BigNumber,
          BigNumber,
          number,
          number,
          number,
          string
        ] & {
          assetType: number;
          owner: string;
          assetAddress: string;
          assetID: BigNumber;
          assetQuantity: BigNumber;
          lockStatus: number;
          approvalStatus: number;
          claimStatus: number;
          claimedBy: string;
        }
      ] & {
        lockBoxOwner: string;
        expiryTime: BigNumber;
        status: number;
        assetA: [
          number,
          string,
          string,
          BigNumber,
          BigNumber,
          number,
          number,
          number,
          string
        ] & {
          assetType: number;
          owner: string;
          assetAddress: string;
          assetID: BigNumber;
          assetQuantity: BigNumber;
          lockStatus: number;
          approvalStatus: number;
          claimStatus: number;
          claimedBy: string;
        };
        assetB: [
          number,
          string,
          string,
          BigNumber,
          BigNumber,
          number,
          number,
          number,
          string
        ] & {
          assetType: number;
          owner: string;
          assetAddress: string;
          assetID: BigNumber;
          assetQuantity: BigNumber;
          lockStatus: number;
          approvalStatus: number;
          claimStatus: number;
          claimedBy: string;
        };
      }
    >;

    owner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateBoxFee(
      _fee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    withdrawFunds(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  approveAsset(
    _id: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  boxFee(overrides?: CallOverrides): Promise<BigNumber>;

  cancelLockBox(
    _id: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  claimAsset(
    _id: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  counter(overrides?: CallOverrides): Promise<BigNumber>;

  createLockBox(
    _assetAtype: BigNumberish,
    _assetAaddress: string,
    _assetAID: BigNumberish,
    _assetAQuantity: BigNumberish,
    _assetBtype: BigNumberish,
    _assetBaddress: string,
    _assetBID: BigNumberish,
    _assetBQuantity: BigNumberish,
    _expiryTime: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  lockAsset(
    _id: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  lockBoxInfo(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [
      string,
      BigNumber,
      number,
      [
        number,
        string,
        string,
        BigNumber,
        BigNumber,
        number,
        number,
        number,
        string
      ] & {
        assetType: number;
        owner: string;
        assetAddress: string;
        assetID: BigNumber;
        assetQuantity: BigNumber;
        lockStatus: number;
        approvalStatus: number;
        claimStatus: number;
        claimedBy: string;
      },
      [
        number,
        string,
        string,
        BigNumber,
        BigNumber,
        number,
        number,
        number,
        string
      ] & {
        assetType: number;
        owner: string;
        assetAddress: string;
        assetID: BigNumber;
        assetQuantity: BigNumber;
        lockStatus: number;
        approvalStatus: number;
        claimStatus: number;
        claimedBy: string;
      }
    ] & {
      lockBoxOwner: string;
      expiryTime: BigNumber;
      status: number;
      assetA: [
        number,
        string,
        string,
        BigNumber,
        BigNumber,
        number,
        number,
        number,
        string
      ] & {
        assetType: number;
        owner: string;
        assetAddress: string;
        assetID: BigNumber;
        assetQuantity: BigNumber;
        lockStatus: number;
        approvalStatus: number;
        claimStatus: number;
        claimedBy: string;
      };
      assetB: [
        number,
        string,
        string,
        BigNumber,
        BigNumber,
        number,
        number,
        number,
        string
      ] & {
        assetType: number;
        owner: string;
        assetAddress: string;
        assetID: BigNumber;
        assetQuantity: BigNumber;
        lockStatus: number;
        approvalStatus: number;
        claimStatus: number;
        claimedBy: string;
      };
    }
  >;

  owner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateBoxFee(
    _fee: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  withdrawFunds(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    approveAsset(_id: BigNumberish, overrides?: CallOverrides): Promise<void>;

    boxFee(overrides?: CallOverrides): Promise<BigNumber>;

    cancelLockBox(_id: BigNumberish, overrides?: CallOverrides): Promise<void>;

    claimAsset(_id: BigNumberish, overrides?: CallOverrides): Promise<void>;

    counter(overrides?: CallOverrides): Promise<BigNumber>;

    createLockBox(
      _assetAtype: BigNumberish,
      _assetAaddress: string,
      _assetAID: BigNumberish,
      _assetAQuantity: BigNumberish,
      _assetBtype: BigNumberish,
      _assetBaddress: string,
      _assetBID: BigNumberish,
      _assetBQuantity: BigNumberish,
      _expiryTime: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    lockAsset(_id: BigNumberish, overrides?: CallOverrides): Promise<void>;

    lockBoxInfo(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        BigNumber,
        number,
        [
          number,
          string,
          string,
          BigNumber,
          BigNumber,
          number,
          number,
          number,
          string
        ] & {
          assetType: number;
          owner: string;
          assetAddress: string;
          assetID: BigNumber;
          assetQuantity: BigNumber;
          lockStatus: number;
          approvalStatus: number;
          claimStatus: number;
          claimedBy: string;
        },
        [
          number,
          string,
          string,
          BigNumber,
          BigNumber,
          number,
          number,
          number,
          string
        ] & {
          assetType: number;
          owner: string;
          assetAddress: string;
          assetID: BigNumber;
          assetQuantity: BigNumber;
          lockStatus: number;
          approvalStatus: number;
          claimStatus: number;
          claimedBy: string;
        }
      ] & {
        lockBoxOwner: string;
        expiryTime: BigNumber;
        status: number;
        assetA: [
          number,
          string,
          string,
          BigNumber,
          BigNumber,
          number,
          number,
          number,
          string
        ] & {
          assetType: number;
          owner: string;
          assetAddress: string;
          assetID: BigNumber;
          assetQuantity: BigNumber;
          lockStatus: number;
          approvalStatus: number;
          claimStatus: number;
          claimedBy: string;
        };
        assetB: [
          number,
          string,
          string,
          BigNumber,
          BigNumber,
          number,
          number,
          number,
          string
        ] & {
          assetType: number;
          owner: string;
          assetAddress: string;
          assetID: BigNumber;
          assetQuantity: BigNumber;
          lockStatus: number;
          approvalStatus: number;
          claimStatus: number;
          claimedBy: string;
        };
      }
    >;

    owner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    updateBoxFee(_fee: BigNumberish, overrides?: CallOverrides): Promise<void>;

    withdrawFunds(overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;
  };

  estimateGas: {
    approveAsset(
      _id: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    boxFee(overrides?: CallOverrides): Promise<BigNumber>;

    cancelLockBox(
      _id: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    claimAsset(
      _id: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    counter(overrides?: CallOverrides): Promise<BigNumber>;

    createLockBox(
      _assetAtype: BigNumberish,
      _assetAaddress: string,
      _assetAID: BigNumberish,
      _assetAQuantity: BigNumberish,
      _assetBtype: BigNumberish,
      _assetBaddress: string,
      _assetBID: BigNumberish,
      _assetBQuantity: BigNumberish,
      _expiryTime: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    lockAsset(
      _id: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    lockBoxInfo(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateBoxFee(
      _fee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    withdrawFunds(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    approveAsset(
      _id: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    boxFee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    cancelLockBox(
      _id: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    claimAsset(
      _id: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    counter(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    createLockBox(
      _assetAtype: BigNumberish,
      _assetAaddress: string,
      _assetAID: BigNumberish,
      _assetAQuantity: BigNumberish,
      _assetBtype: BigNumberish,
      _assetBaddress: string,
      _assetBID: BigNumberish,
      _assetBQuantity: BigNumberish,
      _expiryTime: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    lockAsset(
      _id: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    lockBoxInfo(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateBoxFee(
      _fee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    withdrawFunds(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
